### ISSUE TITLE
Configuration file not used with "gren release", but works with "gren changelog"

### ISSUE THREAD

**Issue by ebousse** [github-tools/github-release-notes#110]
To avoid having to always write the option `--data-source=commits`, I have created a configuration file called `.grenrc.json` with this content:
```
{
    "dataSource": "commits"
}
```
Then in the same folder I try to do a github release, and we see that it only searches for issues, not commits, therefore creating a release with 0 issues (because there is none):
```
$ gren release --override             

🤖  - Generate release notes:
===================================

Getting the list of releases : ...... (0.53 secs)
1 releases found

Getting tags : .... (0.35 secs)
Tags found: 2.4.0

Getting the tag dates ranges : .... (0.32 secs)
Creating the body blocks from releases:

Getting all closed issues : ...... (0.54 secs)
2.4.0 has 0 issues found	

Updating latest release : .... (0.34 secs)

2.4.0 has been successfully updated!
```

But if I do a `git changelog`, it does use the configuration file, because it correctly creates the list of commits in `CHANGELOG.md`.

Am I missing something?

thanks for your tool!

**Comment by alexcanessa** [comment]
@ebousse mmh.. 😕 let me investigate this and I'll come back to you 👍

**Comment by ebousse** [comment]
thanks! I'll give it a try ASAP

**Comment by alexcanessa** [comment]
@ebousse brilliant, thanks. Let me know.
