### ISSUE TITLE
Need some help creating notes from milestone.

### ISSUE THREAD

**Issue by lauhakari** [github-tools/github-release-notes#117]
Hey!

So found this package and thought it would make my day. Unfortunately It's not working as expected. What I am trying to do is build release notes based on issues with a milestone, but when I use _--data-source=milestones_ I just get empty notes.

My tags and milestones should match, i.e be the same and I am trying to run this for example:
`gren release --tags=v1.6.0 --only-milestones -o`.

Any help would be hugely appreciated.

**Comment by alexcanessa** [comment]
Hello @lauhakari,

So you want to build release notes using Milestones as issue wrappers.

Keep in mind that you might have to specify a different `--milestone-match` ([see details here](https://github-tools.github.io/github-release-notes/options.html#milestone-match)) to match the Milestone titles (default `Release {tag_name}`).

So you should, if your milestone title is `Release v1.6.0` and your tag is `1.6.0`, the final command would be:

```bash
gren release --data-source=milestones --milestone-match="Release v{{tag_name}}" --override
```

Does it help?

**Comment by lauhakari** [comment]
Hmm not really, must be misunderstanding something. I just get one line of issue, which is a lot older than the expected release.
Here's some details. Tag = v1.6.0 | Milestone = v1.6.0 .
Issues that were done are tagged with the milestone, and closed now. The commands I am tried runnig are.
`gren release --tags=v1.6.0 --data-source=milestone --milestone-match="{{tag_name}}"`
`gren release --tags=v1.6.0 --data-source=milestone --milestone-match="v{{tag_name}}"`

Also tried with changing the milestone name to "Realease v1.6.0" and then running
`gren release --tags=v1.6.0 --data-source=milestone --milestone-match="Release {{tag_name}}"`, but the same everytime.

**Comment by alexcanessa** [comment]
Based on what you're saying

```
gren release --tags=v1.6.0 --data-source=milestone --milestone-match="{{tag_name}}"
```

Should have work, what's the outcome in the terminal?

**Comment by lauhakari** [comment]
Thanks for the help. :)

So the output I get is the following
```bash
🤖  - Generate release notes:
===================================
✔ Releases found: 17
✔ Tags found: v1.6.0, v1.5.2
✔ Issues found: 10
✔ v1.6.0 has been successfully updated!

URL to release notes.
```
But still just one issue which is done before the release/tag and it doesn't even have a milestone on it.

Does it matter that the repo is private?

**Comment by alexcanessa** [comment]
@lauhakari it doesn't: if it was a permission problem it would have complained about it.

I guess you're running it with the latest version of `gren` (`0.13.1`) (to check just run:

```
gren -v
```

**Comment by lauhakari** [comment]
Yep 0.13.1, just installed it this morning :)

**Comment by alexcanessa** [comment]
ok @lauhakari, I'll do a couple of tests and let you know ASAP

**Comment by alexcanessa** [comment]
@lauhakari all good on my side, quick chat on Gitter? https://gitter.im/github-release-notes/Lobby

**Comment by alexcanessa** [comment]
So looks like there is an issue with passing options, as it works fine when using a `.grenrc` config file.

So the options issue needs a bit more of an investigation
