### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by RobAustin** [github-tools/github-release-notes#127]
I'm getting the following issue ( see below ) when using gren with a private repo, how is this URL generated for the API, this is the URL for my release notes page 

```
https://github.com/ChronicleEnterprise/Chronicle-Fix-Demo/releases
```

🤖  - Generate release notes:
===================================
⠴ Getting the list of releases{ Error: 404 error making request GET https://api.github.com/repos/ChronicleEnterprise/Chronicle-Fix-Demo/releases: "Not Found"
    at new ResponseError (/usr/lib/node_modules/github-release-notes/node_modules/github-api/dist/components/Requestable.js:50:118)
    at handler (/usr/lib/node_modules/github-release-notes/node_modules/github-api/dist/components/Requestable.js:373:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  path: '/repos/ChronicleEnterprise/Chronicle-Fix-Demo/releases',
  request: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json;charset=UTF-8',
        Authorization: 'token dcad189a331b3561cfa6fc652c13b82a7ed713c2',
        'User-Agent': 'axios/0.15.3' },
     method: 'GET',
     url: 'https://api.github.com/repos/ChronicleEnterprise/Chronicle-Fix-Demo/releases',
     params: { per_page: 99, page: 1 },
     data: undefined,
     responseType: 'json' },

**Comment by alexcanessa** [comment]
Hello @RobAustin,

Does the `token` you've generated have all `repo` scopes?

**Comment by RobAustin** [comment]
thanks that fixed it.
