### ISSUE TITLE
Template: PR branch name?

### ISSUE THREAD

**Issue by svanzoest** [github-tools/github-release-notes#131]
Hi,

Based on the data test fixtures, it seems like this might be tricky, but I would love to be able to have access to the branch name, so I could post process it in template to create the CHANGELOG. 

I couldn't find if this was available currrently.

**Comment by alexcanessa** [comment]
Hi @svanzoest the only problem with this task is that right now we're using the `issue` API to get PRs (as a `pull_request` is - technically - an `issue`).

### The Solution:

1. Call the [get single PR](https://developer.github.com/v3/pulls/#get-a-single-pull-request) when the `issue` has been identified as PR:
https://github.com/github-tools/github-release-notes/blob/3e6b2e40e20a1abca065bfacad58d25164c1d1db/lib/src/Gren.js#L784-L789
2. Pass the `branch` information to the `template` function:
https://github.com/github-tools/github-release-notes/blob/3e6b2e40e20a1abca065bfacad58d25164c1d1db/lib/src/Gren.js#L472-L479
