### ISSUE TITLE
Sort tags by date before fetching release notes

### ISSUE THREAD

**Issue by alexcanessa** [github-tools/github-release-notes#134]
[GitHub APIs tags](https://developer.github.com/v3/repos/#list-tags) returns a list of tags ordered by name (as `git tag --list` does).

We have to order them per date or the functionality will break.

**Comment by wellDan28** [comment]
@alexcanessa you can use the  [github graphql api](https://developer.github.com/v4/explorer/) to get the result ordered by date.

For example:
`{
  repository(owner: "github-tools", name: "github-release-notes") {
    refs(refPrefix:"refs/tags/", last:100, orderBy:{field:TAG_COMMIT_DATE, direction: ASC}) {
      nodes {
        name
      }
    }
  }
}
`

**Comment by wellDan28** [comment]
@alexcanessa are you working on this issue? 
can I try fixing it?

**Comment by alexcanessa** [comment]
I've actually started looking into it, but not deeply. You're more than welcome to have a look.

Keep in mind that there is a function that gets the dates of the tags, so far used for other functionality but that could easily be implemented before in the flow and avoid this bug:

https://github.com/github-tools/github-release-notes/blob/3e6b2e40e20a1abca065bfacad58d25164c1d1db/lib/src/Gren.js#L332-L342

**Comment by wellDan28** [comment]
It's look there is already a function for sorting by dates :
https://github.com/github-tools/github-release-notes/blob/3e6b2e40e20a1abca065bfacad58d25164c1d1db/lib/src/Gren.js#L856-L858

I think the real problem is that the paging not working, as I reported in  #132 
The sorting is working but not on all tags are exists.

**Comment by alexcanessa** [comment]
Fixed in [0.17.1](https://github.com/github-tools/github-release-notes/releases/tag/0.17.1)
