### ISSUE TITLE
Optionally create release notes to a text file.

### ISSUE THREAD

**Issue by RobAustin** [github-tools/github-release-notes#138]
Gren is a great tool - is it possible to use Gren to generate the release notes to a file. I see it's possible for the change log but this would be a good feature to have for the release notes.

**Comment by alexcanessa** [comment]
Hey @RobAustin, actually you can, by tweaking a bit the options:

## 1. Templates

You can change the output of each line via a [configuration file](https://github-tools.github.io/github-release-notes/options.html#templates)

If you don't want a markdown output then, you could use something like:

```
{
   "template": {
      "changelogTitle": "Changelog\n\n",
      "group": "\n - {{heading}}\n",
      "release": "{{release}} ({{date}})\n{{body}}",
      ...
   }
}
```

(and so on)

## 2. Filename option

You can change the output file of the `changelog` action.
[Follow this link](https://github-tools.github.io/github-release-notes/options.html#changelog-filename) to read more about it.

So it could easily be `file.txt`.

## HEADS UP! ⚠️ 

**I haven't tested this myself, I'm just assuming it would work**

**Comment by RobAustin** [comment]
thanks
