### ISSUE TITLE
Feature to be able to specify limit on tags for the changelog

### ISSUE THREAD

**Issue by phun-ky** [github-tools/github-release-notes#144]
I want to be able to run:

    gren changelog --limit-tags=30

Generating the release for just the 30 latest releases, so I don't get a huge file after some months of continuous development.

The feature should add a template string on the bottom of the changelog, like: "To see the full list" -> Point to releases

**Comment by alexcanessa** [comment]
There is already a sparkle of it in here. By editing this line, it should be quite easy.

https://github.com/github-tools/github-release-notes/blob/3e6b2e40e20a1abca065bfacad58d25164c1d1db/lib/src/Gren.js#L52-L52
