### ISSUE TITLE
Commit author's name link is incorrect

### ISSUE THREAD

**Issue by jfix** [github-tools/github-release-notes#158]
I've just started using `gren` so maybe this is just bad usage on my part.

I've configured `gren` with the CLI (very nice 👍), and this is the config file:

```
---
  dataSource: "commits"
  prefix: ""
  includeMessages: "all"
  changelogFilename: "CHANGELOG.md"
```

I've generated the Changelog for an existing release via `gren release --override`. While this works well, I've noticed that each list item ends with the author name which is supposed to be clickable.  I don't know why, but in my case, it uses my name, "Jakob Fix", instead of my id, @jfix. Therefore, because of the prefixed @ it makes the first name, @Jakob, clickable, which is another Github user.

Here's an example from the `CHANGELOG.md` file which I also generated using `gren changelog --override`:

```
- [✨ Replace `electron-json-storage` with `electron-store` (dot notation!).](https://api.github.com/repos/jfix/pac-toolkit/git/commits/3a65f60133ea288e294266e69a26875af6ea4df6) - @Jakob Fix
```

I've added the configuration option `username: "jfix"` to the configuration file, hoping this would change things, but to no avail, unfortunately.

Here is the release: https://github.com/jfix/pac-toolkit/releases/tag/v1.1.0

**Comment by alexcanessa** [comment]
Hey @jfix, thanks for your feedback.

This one can be easily tackled by changing what gets passed to the template.

https://github.com/github-tools/github-release-notes/blob/78786b31a7a85afc884092af41c681669fe9652e/lib/src/Gren.js#L429-L436

**Comment by alexcanessa** [comment]
I just realised that what the GitHub APIs come back with, doesn't contain the `username` but just the `name`

```json
{
  "sha": "7638417db6d59f3c431d3e1f261cc637155684cd",
  "url": "https://api.github.com/repos/octocat/Hello-World/git/commits/7638417db6d59f3c431d3e1f261cc637155684cd",
  "author": {
    "date": "2014-11-07T22:01:45Z",
    "name": "Scott Chacon",
    "email": "schacon@gmail.com"
```

https://developer.github.com/v3/git/commits/#get-a-commit

**Comment by alexcanessa** [comment]
This is actually still a bug as the `author` we're looking for doesn't belong to `commit`.

See: https://api.github.com/repos/github-tools/gren-tester/commits/2235967d392fb3822c4a9a9f908d18d80a541268
