### ISSUE TITLE
Request to release a new version

### ISSUE THREAD

**Issue by itaym2** [github-tools/github-release-notes#168]
Hi,
First I want to say thanks for building & maintaining this project. It's really useful & helpful.

Second, I would like to request that you release the latest version of the project to npm. The last release was made on January. Since then there were several PRs merged, some of them solves existing bugs which make the project unusable for some of my repos.

Is it possible to release a new version with the merged PRs?

Thanks,
Itay.

**Comment by alexcanessa** [comment]
Hi @itaym2 you're definitely right.

The new release is going out this Saturday! Stay tuned 🎉

**Comment by alexcanessa** [comment]
@itaym2 @kyeah `0.16.0` is out!

https://github.com/github-tools/github-release-notes/releases/tag/0.16.0
