### ISSUE TITLE
Group issues by first label matching a group

### ISSUE THREAD

**Issue by kyeah** [github-tools/github-release-notes#169]
Hi! This is a minor detail, but I think it'd be nice to always group an issue under a header if one exists, instead of grabbing the first label from the issue. e.g. if we're grouping by:

```
Added: ['added'],
Updated: ['updated'],
Removed: ['removed']
```

and an issue is labeled as [`experiment`, `updated`], it seems like it'll pick up `experiment` and leave the issue out of the commit notes, when the usual intention is to group under `updated`.

**Comment by alexcanessa** [comment]
That's indeed an unexpected behaviour.

According to this, it should include the issue if the list of its labels includes the one defined in the group.

https://github.com/github-tools/github-release-notes/blob/837d4b2c13c8cfdf7fe48bb991d2a9dce0e5c8d1/lib/src/Gren.js#L801

Do you have an actual live example?

**Comment by kyeah** [comment]
ah, I was skimming through `groupByLabel` and hadn't taken the time to test this out locally. The above snippet should handle this as expected — confirmed after testing. thanks!
