### ISSUE TITLE
Fun fact: your page breaks google SERP

### ISSUE THREAD

**Issue by mlbrgl** [github-tools/github-release-notes#170]
Not an issue at all (for you at least), but more of a curiosity: when typing "github release notes" in google search, here is what I see:

![capture d ecran 2018-05-29 a 11 21 54](https://user-images.githubusercontent.com/13406362/40650137-d9a81b1a-6332-11e8-9f7c-627c7cedb647.png)

Tried in a couple of browsers, same result. Didn't find any other "rogue" Github project that triggers a similar result.

**Comment by alexcanessa** [comment]
Ha! That's interesting 🤔

**Comment by alexcanessa** [comment]
I think they just solved the problem 👍 (👎)
