### ISSUE TITLE
Abbreviated Commit Hash

### ISSUE THREAD

**Issue by riipandi** [github-tools/github-release-notes#182]
Hi, can I print abbreviated commit hash in commit template? If yes, how?

Thanks.

**Comment by alexcanessa** [comment]
Hello,

[GitHub commits API](https://developer.github.com/v3/repos/commits/#get-a-single-commit) only has a full SHA. But I believe the shorter version it's just a substring of it?

So, in your `.grenrc.js` file, you can have something like:

```javascript
module.exports = {
  template: {
    commit: ({ sha }) => {
      return `-${sha.substring(0, 7)}`;
```

**Comment by riipandi** [comment]
Ok, thank you
