### ISSUE TITLE
Include all PR merged since last tag when data source is commits

### ISSUE THREAD

**Issue by mlrv** [github-tools/github-release-notes#213]
Hi, I'm trying to achieve the following:

- master branch is on tag `v0.0.x`
- branch `feat-branch-1` has the following commits
  - `feat-1-commit-1`
  - `feat-2-commit-2`
- branch `feat-branch-2` has the following commits
  - `feat-2-commit-1`
  - `feat-2-commit-2`
- first, I open a PR to merge `feat-branch-1` and I squash the two commits, so that only one new commit is added to the master branch
- then, I do the same thing for `feat-branch-2`, so another new commit is added to master

What I'd like to do at this point is to use `gren` to generate release notes which include the two squashed commits from `feat-branch-1` and `feat-branch-2`, something like

```
- Second squashed commit message (#2) - @mlrv
- First squashed commit message (#1) - @mlrv
```

but running `gren release --data-source=commits` only seems to include the very last commit, am I doing something wrong?

**Comment by mlrv** [comment]
I have done some further investigation and it actually seems that the release notes include all commits apart from the very first one that came after the previous release.

I.e.

- previous release @ commit `#7`
- commit `#8`
- commit `#9`
- commit `#10`

If I release now, the notes will only include `#9` and `#10`

**Comment by svanzoest** [comment]
I think this might be related to #181

**Comment by mlrv** [comment]
Yup, seems to be the same kind of problem, I'll close this as a duplicate. Thanks @svanzoest
