### ISSUE TITLE
My repository not have tags. Only some braches in here? What should I do to gren my release note?

### ISSUE THREAD

**Issue by guoxunbo** [github-tools/github-release-notes#214]
Hi. Thank grens.
As the title say. The repository only have some branches and milestones.  what should i do to generator my release notes. version is 0.17.
Thanks a lot.

**Comment by guoxunbo** [comment]
Please look this image. There is no imges.  What should i to add?
![image](https://user-images.githubusercontent.com/14329149/62356420-9f350880-b543-11e9-9930-28d99fd06a8c.png)

**Comment by yansheng836** [comment]
Release is depends on tag,you should add tags in you project.

**Comment by alexcanessa** [comment]
As @yansheng836 said, there isn't much we can do.
