### ISSUE TITLE
[feature request] sharing config or online config

### ISSUE THREAD

**Issue by levy9527** [github-tools/github-release-notes#217]
Thanks gren, we use it a lot and it saves our time.

We have many repos(https://github.com/femessage) using gren with the same `.grenrc.js`.

Now the problem is when we want a new config, we should update all the repos' `.grenrc.js` , that's frustrating and faulty.

So it's there any plan to support sharing config like https://prettier.io/docs/en/configuration.html#sharing-configurations or getting config via a Github repo file?

Waiting for your response😄

**Comment by alexcanessa** [comment]
Should be done by #230
