### ISSUE TITLE
ignoreIssuesWith in .grenrc not working

### ISSUE THREAD

**Issue by BasvanH** [github-tools/github-release-notes#221]
Hello,

I have the following config:
```
{
    "dataSource": "commits",
    "groupBy": false,
    "changelogFilename": "CHANGELOG.md",
	"ignoreIssuesWith": [
        "wontfix",
        "duplicate",
        "question"
    ]
}
```

No matter what datasource I set, the ```ignoreIssuesWith``` is not used. Issues with this label are being added to releases and changelog.

Is this not how it supposed to work?

Kind regards,
Bastiaan

**Comment by alexcanessa** [comment]
@BasvanH what command are you running?

**Comment by BasvanH** [comment]
@alexcanessa, thats ```npm run dev```

**Comment by BasvanH** [comment]
Sorry, I'm no longer using your plugin.
