### ISSUE TITLE
configure multiple tokens?

### ISSUE THREAD

**Issue by mattnworb** [github-tools/github-release-notes#225]
Hi, is it possible to configure multiple tokens, i.e. one for github.com and another for GHE? 

From what I can tell, it looks like the token can only be configured in an environment variable named `GREN_GITHUB_TOKEN` (or `--token`). For people working on repos that are a mixture of github.com repos and private GHE repos, it'd be great if there was a way to have two tokens configured.

**Comment by alexcanessa** [comment]
@mattnworb interesting. What kind of API did you have in mind?

**Comment by mattnworb** [comment]
@alexcanessa good question. On second thought, I'm not really sure that there would be any easy way for gren to know which token or which environment variable I want to use 😀

**Comment by alexcanessa** [comment]
@mattnworb yeh it's a bit difficult, I'll close it for now, until we have an idea for a nice API
