### ISSUE TITLE
The number of  commits will be reduced by one when "--data-source=commits"

### ISSUE THREAD

**Issue by yansheng836** [github-tools/github-release-notes#229]
## Problem
When I use the "--data-source=commits" to grenerte the releases , the commits information will be incorrect. If there is only one commit between the versions, then the commits information will be displayed. If there are two or more submissions, one less commits will be displayed, as follows:

### my command :

```bash
gren release --tags=all --data-source=commits  --override --token=my_token
```

### git log:
![file](http://bucket836.oss-cn-shenzhen.aliyuncs.com/image-1575213720888.png)

### releases:
![file](http://bucket836.oss-cn-shenzhen.aliyuncs.com/image-1575213895891.png)

![file](http://bucket836.oss-cn-shenzhen.aliyuncs.com/image-1575213856124.png)

## gren version

```bash
$ gren -v
0.17.0
```

**Comment by alexcanessa** [comment]
Fixed by 2460facf950c3351a6cd7f642ffac10f4b965388
