### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by blairg23** [github-tools/github-release-notes#231]
Based on #228, this product is currently unusable and I'm curious if anyone else just hasn't noticed or isn't on the version that is broken... I haven't seen a commit since October and the one before that was February... is anyone even looking at these issues?

**Comment by alexcanessa** [comment]
Hello @blairg23 

I've been a bit busy recently but I'm actually looking at all the issues now, mapping them and going into a bit of a refactor 😄

**Comment by JuergenSimon** [comment]
@blairg23 you could always contribute :)

**Comment by alexcanessa** [comment]
I'm closing this issue as isn't really helping tracking anything.
