### ISSUE TITLE
Gren fails when used on first release

### ISSUE THREAD

**Issue by donmahallem** [github-tools/github-release-notes#255]
Hi.

I ran into an issue when using gren for the very first release.
It will crash due to undefined being inside the selectedTags array.
https://github.com/github-tools/github-release-notes/blob/617cb77fe9a710556c367e459b9bf7088d9538a5/lib/src/Gren.js#L1132
This is due to releaseDates only containing one item in these lines:
https://github.com/github-tools/github-release-notes/blob/617cb77fe9a710556c367e459b9bf7088d9538a5/lib/src/Gren.js#L1129-L1130
 and trying to retrieve two which leads to selectedTags to contain an undefined as second element which will cause an 

> TypeError: Cannot read property 'name' of undefined

in line 1132 as referenced above.

**Comment by alexcanessa** [comment]
Good catch, thanks

**Comment by brettcurtis** [comment]
When can we expect this to be released ? I'm hoping to use this in some of our pipelines and having same issue.

**Comment by alexcanessa** [comment]
@brettcurtis the release that includes this should be rolled out on Monday. I'll keep you posted on this issue.

**Comment by alexcanessa** [comment]
@brettcurtis release done https://github.com/github-tools/github-release-notes/releases/tag/0.17.2

Please let me know if it's all fixed :)

**Comment by brettcurtis** [comment]
Hmm, still failing - it's highly possible I'm doing something wrong:

```gren release
Getting gren config from local file /home/brett/repos/my-org/terraform-google-billing-budget/.grenrc.js

🤖  - Generate release notes:
===================================
✔ Releases found: 0
⠸ Getting tagsTypeError: Cannot read property 'name' of undefined
    at /usr/local/lib/node_modules/github-release-notes/dist/Gren.js:1936:55
    at Array.map (<anonymous>)
    at Gren._callee18$ (/usr/local/lib/node_modules/github-release-notes/dist/Gren.js:1935:70)
    at tryCatch (/usr/local/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/github-release-notes/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/github-release-notes/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I can get it to run when I add the tag:

```gren release --tags=1.0
Getting gren config from local file /home/brett/repos/my-org/terraform-google-billing-budget/.grenrc.js

🤖  - Generate release notes:
===================================
✔ Releases found: 0
✔ Tags found: 1.0
✔ Issues found: 1
✔ v1.0 has been successfully created!
See the results here: https://github.com/my-org/terraform-google-billing-budget/releases/tag/1.0```

**Comment by donmahallem** [comment]
I just did a quick test with a new clean repo and 0.17.2.

It does appear that the fix isn't included in this release. If I look into the distributed source it doesn't appear to be there.

![grenissue](https://user-images.githubusercontent.com/4698322/80397824-0905f700-88b7-11ea-9bc0-c1df955ce208.jpg)

**Comment by alexcanessa** [comment]
🤦 my bad.

Please check 0.17.3

**Comment by brettcurtis** [comment]
Looks good thanks!
