### ISSUE TITLE
Add possibility to change date format

### ISSUE THREAD

**Issue by phun-ky** [github-tools/github-release-notes#27]
It should be possible to specify date format other than US

**Comment by alexcanessa** [comment]
@phun-ky could be related to #23. Definitely a good suggestion.

**Comment by alexcanessa** [comment]
We can add functions as template properties, so to evaluate wherever you want to customise.

P.S. The default date format is DD/MM/YYYY right now.

**Comment by urbanyeti** [comment]
Several years later but but it took me awhile to figure out how to do this with templates in a .grenrc.js file so I thought I would share what I used to convert DD/MM/YYYY to YYYY/MM/DD

`	"template": {
		release: function (placeholders) {
			var parts = placeholders.date.split("/");
			var dt = new Date(parseInt(parts[2], 10),
                  parseInt(parts[1], 10) - 1,
                  parseInt(parts[0], 10));
            return '## ' + placeholders.release + ' (' + dt.toISOString().substring(0, 10).replace(/-/g,"/") +")\n" + placeholders.body;
		}
    }`
