### ISSUE TITLE
You need to have network connectivity

### ISSUE THREAD

**Issue by DawoudIO** [github-tools/github-release-notes#28]
looking to use this inside a vagrant box, but keep getting the following error

`You need to have network connectivity` 

see my [package.json ](https://github.com/ChurchCRM/CRM/blob/8bb40d45a796c943d6aead826217e5aaae0931c9/package.json)

![image](https://cloud.githubusercontent.com/assets/554959/22636190/561e5708-ebee-11e6-91c9-f30ad4101eb6.png)

**Comment by DawoudIO** [comment]
hi @alexcanessa any luck ?

**Comment by alexcanessa** [comment]
Hi @DawoudIO we're investigating, I'll let you know as soon as we find a solution.

**Comment by alexcanessa** [comment]
@DawoudIO I've tried to replicate the issue inside vagrant but I couldn't.

Do you have any particular configuration for the network inside vagrant?

**Comment by DawoudIO** [comment]
Thank you for looking at it...

We extended scotch.io's box see https://github.com/ChurchCRM/VagrantBox

No network changes

**Comment by alexcanessa** [comment]
@DawoudIO In the next few days, there will be a release (**0.6.0**) which will hopefully provide more insight into what errors are occurring and where. This should help us identify what exactly is the error you are getting.

Stay tuned.

**Comment by DawoudIO** [comment]
Thanks looking forward to testing it

**Comment by alexcanessa** [comment]
@DawoudIO try to install version 0.6.0 (latest) and run it again.

**Comment by DawoudIO** [comment]
Tried and got 0.6.1 

![image](https://cloud.githubusercontent.com/assets/554959/23833729/e7c26bb2-0706-11e7-9ac0-395b460cc46a.png)

**Comment by alexcanessa** [comment]
@DawoudIO Oh, here we are.

Looks like you're running the task in a non-git environment (or at least where `git config user.name` has not been defined).

Since we don't actually need that information, I can do a quick patch this morning and in an hour you can use the tool.

This issue will be fixed as #45

**Comment by alexcanessa** [comment]
@DawoudIO Try now with `0.6.2` :)

**Comment by DawoudIO** [comment]
better 

```
vagrant@scotchbox:/vagrant$ gren --username=CRM --repo=ChurchCRM --token=xyz

Task(s) stopped because of the following error:
[TypeError: Cannot assign to read only property '0' of [object String]]
```

**Comment by alexcanessa** [comment]
@DawoudIO LoL.

Alright, I'll come back to you soon :)

**Comment by DawoudIO** [comment]
Thanks for the help

**Comment by alexcanessa** [comment]
@DawoudIO join the [gitter chat](https://gitter.im/github-release-notes/Lobby), so we can face it better! 😄

**Comment by alexcanessa** [comment]
@DawoudIO Wait, are you actually running it with `--token=xyz`?

The token has to be a ![generated token](https://github.com/github-tools/github-release-notes/#github-informations)

I also think repo and username might be wrong. Are you trying to run release notes for https://github.com/ChurchCRM/CRM?

You need to generate the token and then run the command with:

```
gren --username=ChurchCRM --repo=CRM --token=YOUR_TOKEN_HERE
```

**Comment by alexcanessa** [comment]
@DawoudIO I was able to replicate it. Leave it with me

**Comment by alexcanessa** [comment]
@DawoudIO Release `0.6.3` 🤞

**Comment by DawoudIO** [comment]
looking much better great work

```
Release task:
===================================
Getting the list of releases: ......... (0.89 secs)
29 releases found
Getting tags: .... (0.37 secs)
Tags found: 2.6.1, 2.6.0
Getting the tag dates ranges: .... (0.34 secs)
Creating the body blocks from releases:
Getting all closed issues: ................................. (3.23 secs)
27 issues found
Skipping 2.6.1 (use --override to replace it)
```

now i have to learn to use the plugin and get `grunt-github-release-notes` worknig

thank you so much

**Comment by alexcanessa** [comment]
@DawoudIO The [grunt-github-release-notes@0.5.0](https://github.com/github-tools/grunt-github-release-notes) has been updated to use the latest version

**Comment by DawoudIO** [comment]
thanks I'll test with that..
