### ISSUE TITLE
Handle the 401 Error

### ISSUE THREAD

**Issue by alexcanessa** [github-tools/github-release-notes#4]
Handle errors regarding the token.

**Comment by potmo** [comment]
I get a 401 when I have an access token with repo access. If I add access to everything it seems to work but I'm not sure what access that fixes the problem.

I have a private repo btw

**Comment by alexcanessa** [comment]
@potmo The only scope you need for the token is the `repo` access, doesn't matter if the repo is private: if you have access to it, so will the token.

Try to go to your personal `settings > Developer settings > Personal access tokens`, click `edit` next to the token you want to update, and check all the `repo` scopes, as for the screenshot below:

![image](https://cloud.githubusercontent.com/assets/1176495/19184309/64287e20-8c74-11e6-8e55-66860ef1cb48.png)

Let me know if you still have the problem after updating the token.

**Comment by alexcanessa** [comment]
@potmo still an issue?

**Comment by potmo** [comment]
I don't know. I gave up and used something else
