### ISSUE TITLE
Installing old versions of github-release-notes no longer works

### ISSUE THREAD

**Issue by SlowShip** [github-tools/github-release-notes#51]
Hey guys. 

I think recent changes may have broken older versions of github-release-notes

We were using 0.4.0, if I make a brand new package.json with 
```json
{
  "name": "blah",
  "version": "1.0.0",
  "devDependencies": {
    "github-release-notes": "0.4.0",
    "install": "^0.8.7",
    "npm": "^4.4.1"
  }
}
````
and then run `npm install`

It errors out with fatal: Authentication failed for 'https://github.com/alexcanessa/github.git/'

I'm guessing it's because this repo existed in the past but has since been moved to the github-tools org but older versions of github-release-notes don't know that. So; heads up that older versions are broken.

Updating to the latest version of github-release-notes fixed it for us. Don't know if you want to do anything more to mitigate this issue for other people.

Thanks for your time

Josh

**Comment by alexcanessa** [comment]
Sure! Good point.

Thanks for the feedback!
