### ISSUE TITLE
Rework the Changelog generator function

### ISSUE THREAD

**Issue by alexcanessa** [github-tools/github-release-notes#61]
The changelog action now has some `--override` capacity which is not really needed.

What the changelog function should be responsible for should only be to update the current `CHANGELOG.md` using the existing releases.

- The `--override` flag should only be able to override the latest release or a specific tag range.
- Use the `--tags=[]` option to configure the release range too. _optional_
- Would the `changelog` action be able to **create** release notes or should it just be based on the existing ones?

**Comment by alexcanessa** [comment]
@DawoudIO would be good to have your feedback

**Comment by DawoudIO** [comment]
i like --tags[] for a subset of the logs
to me override is a full wipe of the old changelog.md
I'm not sure i understand the last comment about changelog

@crossan007 any feedback on the above items

**Comment by alexcanessa** [comment]
@DawoudIO I was wondering if the `--action=changelog` should be able to create release notes from scratch or should just get the actual release notes (that could have been generated by this module) from Github.

**Comment by crossan007** [comment]
I like the idea of being able to create from scratch.

**Comment by crossan007** [comment]
+1 for --tags[]
