### ISSUE TITLE
Use milestones to create release notes

### ISSUE THREAD

**Issue by alexcanessa** [github-tools/github-release-notes#67]
Give the option to:

1. List only issues that have Milestones, which I imagine would be just an option:
```json
{
    "onlyMilestones": true
}
```
2. Create release notes based on milestones rather then on dates. _only applicable to issues_
To achieve it we need to create a matching system between the tag name and the milestone naming convention.
```json
{
    "dataSource": "milestones",
    "milestoneMatch": "Release {{tag_name}}"
}
```
3. Use the description of the milestone in the release body.
4. Consider to filter only closed milestones (?)

**Comment by alexcanessa** [comment]
@DawoudIO this is a feature that you asked for. If you can add your feedback on top of the description would be nice.

**Comment by DawoudIO** [comment]
Sounds good please let me know when you have the build #
