### ISSUE TITLE
Add the possibility to create a CHANGELOG file

### ISSUE THREAD

**Issue by AurelioDeRosa** [github-tools/github-release-notes#7]
In addition to publishing the changes for a release in GitHub, it'd be nice if the task could create a CHANGELOG file in Markdown.

**Comment by alexcanessa** [comment]
Thanks, it is on the list :+1:

**Comment by ctesene** [comment]
It would also be nice if we **just** wanted the file created. We already have some tooling around creating the release in GitHub, and have a need to generate a ```changelog``` for distribution to other teams (such as QA, etc) so they know what changes were included in the release.
