### ISSUE TITLE
Expanded options for commit template variables

### ISSUE THREAD

**Issue by durera** [github-tools/github-release-notes#72]
Unless I'm mistaken it seems message is the only variable available for templating commit entries. I was hoping to put together a changelog with a format something like:

`[{{sha}}]({{url}}) {{message}} - {{author.name}}`

I was wondering if there's a specific reason why `commitMessages()` just pulls out the commit message rather retaining the commit object (or a subset of it), which can then pass through the system eventually allowing `generateCommitsBody()` to template on more than just the commit message? If not, is this something that could be added?

**Comment by alexcanessa** [comment]
@durera The commit messages as release bodies belong to a very old version of the module, therefore it wasn't expanded yet.

Would you think the whole Object should be exposed or just:

- SHA
- url
- message
- author (the whole Object)

PR?

**Comment by durera** [comment]
I was thinking the whole object personally.  The size of the full commit object shouldn't cause any issues so I can't think of any reason to limit it to a subset of the properties..  

I haven't written any code for it yet.  I've only just started poking around the code today so not sure what the scope/complexity of the change would be at the moment.

**Comment by alexcanessa** [comment]
Closed by #88
