### ISSUE TITLE
`gren --help` quietly does shit

### ISSUE THREAD

**Issue by broofa** [github-tools/github-release-notes#80]
```
kieffer@MacBook-Pro-3$ gren --help

Release task:
===================================
Getting the list of releases: ..... (0.47 secs)
3 releases found
Getting tags: .... (0.32 secs)
Tags found: v2.0.1, v2.0.0
Getting the tag dates ranges: .... (0.38 secs)
Creating the body blocks from releases:
Getting all closed issues: .... (0.34 secs)
2 issues found
Skipping v2.0.1 (use --override to replace it)
```

Uhh... ![image](http://www.reactiongifs.us/wp-content/uploads/2014/10/this_time_doctor_who.gif)

But seriously, having the typical "what's this command do?" incantation result in cryptic output that gives no indication that, "hey, your release notes on Github just got updated, Bub!" kinda sucks.

And, more generally, here's the CLI I would expect:

| Command | Behavior |
| --- | --- |
| `gren --help` |  list usage patterns and exit |
| `gren` (no options) | Alias of `gren --help` |
| `gren release` | Instead of `gren --action=release` |
| `gren changelog` | Instead of `gren --action=changelog` |

Regarding the last two, making the command a dashless argument seems more natural.  Think "git [command]" or "npm [command]".

**Comment by alexcanessa** [comment]
Definitely, you're right and there is an issue for `gren --help` in particular #66.

We're going to introduce [Commander](https://www.npmjs.com/package/commander) in order to provide a better solution in terms of usability.
