### ISSUE TITLE
Ignore commits with keywords

### ISSUE THREAD

**Issue by foxted** [github-tools/github-release-notes#84]
It would be nice when generating the changelog to be able to ignore keywords from commit messages. 

For example, when updating the changelog, I have to make a commit `Update changelog`, but these commits are then included in the changelog. Would be nice to ignore them by adding the keyword `changelog`.

**Comment by alexcanessa** [comment]
Good point @foxted, thanks for your feedback.

**Comment by alexcanessa** [comment]
Closed by #103. Is going to be part of `Release 0.13.0`

**Comment by foxted** [comment]
Awesome!
